version: "3.9"
services:
  web:
    image: node:lts-alpine3.13
    container_name: web
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    env_file: .env
    environment:
      - NODE_ENV=$NODE_ENV
      - PROCESS_TYPE=$PROCESS_TYPE
      - WEB_PORT=$WEB_PORT
      - JWT_SECRET=$JWT_SECRET
      - JWT_ALGO=$JWT_ALGO
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    expose:
      - "$WEB_PORT"
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    restart: unless-stopped
    command: yarn start:dev
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    ports:
      - "$MONGO_PORT:$MONGO_PORT"

volumes:
  dbdata:
